spring:
  profiles.active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/project_tabula
    username: sdvkit
    password: sdvkit-roottoor
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy